<script type="text/javascript">
        $(function() {
      $("#movies").tablesorter();
    }); 
</script>


<table id="movies" class="tablesorter">
<thead>
<tr>
    <th>Title</th>
    <th>Release Date</th>
    <th>Vote Count</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->movies as $movie) {?>
    <tr>
        <td><?php echo $movie->getTitle()?></td>
        <td><?php echo $movie->getReleaseDate()?></td>
        <td><?php echo $movie->getVoteCount()?></td>
    </tr>
<?php } ?>
</tbody>
</table>
